### ISSUE TITLE
instabug is not sending automatic report on error in agnular appications

### ISSUE THREAD

**Issue by ayyazzafar** [Instabug/web-sdk-sample#2]
Hello ! I integrated instabug in my angular app. It works well by using form but it does not automatically detect error in console and does not send automatic reports of errors. 

How can we do this automatically?

**Comment by migaber** [comment]
added to backlog

**Comment by migaber** [comment]
Hello @ayyazzafar, Thank you for your report, and sorry for being late in response.

instabug websdk is now caring about sending bugs reported by users, we didn't implement auto crash reporting yet, we still in beta stage doing our best to ship the bug reporting feature, but be sure we will include this in our technical backlog and will implement it ASAP :)

Thank you very much.
